# Generated by Django 5.1.4 on 2024-12-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lager',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lageraccess',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='lager',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lager',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lageraccess',
            name='lager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lager'),
        ),
    ]
