# Generated by Django 5.1.4 on 2024-12-16 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_lager_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lager',
            name='users',
            field=models.ManyToManyField(related_name='lagers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lager',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menge', models.IntegerField()),
                ('lager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lager')),
            ],
        ),
    ]
